name: Traffic Update

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: 'curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/javanile/vtiger/traffic/popular/referrers'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
