name: Traffic Update

on:
  schedule:
    - cron:  '5 8 * * 0'
  workflow_dispatch:
    inputs:
      name:
        description: 'Update Traffic'
        default: 'Update'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Traffic'
        uses: actions/checkout@v2
      - name: 'Update Traffic'
        run: make update
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Commit Changes'
        uses: stefanzweifel/git-auto-commit-action@v4